### ISSUE TITLE
User experience tweak

### ISSUE THREAD

**Issue by Amalazas** [password-generation/AI-cryptanalysis#27]
- Polish cmd line help and argument passing

**Comment by Amalazas** [comment]
It would be a good idea to spend some time on optimizing the setup of our app - at the moment it takes a pretty long time to get everything ready.

**Comment by Amalazas** [comment]
@domkvv 
Setup time optimization and progress bars are already implemented.

**Comment by domkvv** [comment]
Added stdev and samples_count to config file, changed the name of program if i understood point 3. correctly

**Comment by Amalazas** [comment]
@pietruszkowiec 
Another UX change proposal:
Handle keyboard interrupts so that when the program is interrupted during mangling or generation phase, the current progress is saved before quitting the program.
